# Generated by Django 5.2.13 on 2026-05-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="source_name",
            field=models.CharField(default="123", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
