# Generated by Django 5.2.13 on 2026-05-05 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=11)),
                ("client_name", models.CharField(max_length=30)),
                ("start_date", models.DateTimeField(default=None, null=True)),
                ("end_date", models.DateTimeField(default=None, null=True)),
                ("nn", models.CharField(blank=True, max_length=5)),
                ("send_number", models.CharField(blank=True, max_length=10)),
                ("weight", models.CharField(blank=True, max_length=5)),
                (
                    "area",
                    models.PositiveIntegerField(
                        default=None,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(99)],
                    ),
                ),
            ],
        ),
    ]
