# Generated by Django 5.2.13 on 2026-05-05 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_source_name"),
        ("containers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="containers",
                to="clients.client",
            ),
            preserve_default=False,
        ),
    ]
