# Generated by Django 5.2.13 on 2026-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0002_container_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="status",
            field=models.CharField(
                choices=[("on_station", "На станции"), ("picked_up", "Забран")],
                default="on_station",
                max_length=16,
            ),
        ),
    ]
