# Generated by Django 5.2.13 on 2026-05-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0003_container_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="status",
            field=models.CharField(
                choices=[
                    ("on_station", "На станции"),
                    ("in_booking", "В заявке"),
                    ("picked_up", "Забран"),
                ],
                default="on_station",
                max_length=16,
            ),
        ),
    ]
