# Generated by Django 5.2.13 on 2026-05-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="current_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
