# Generated by Django 5.2.13 on 2026-05-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_slot_current_count"),
        ("containers", "0004_alter_container_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("slot", "container")},
        ),
    ]
