# Generated by Django 5.2.13 on 2026-05-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slot",
            name="current_count",
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активна"),
                    ("cancelled", "Отменена"),
                    ("not_completed", "Не выполнена"),
                    ("completed", "Выполнена"),
                ],
                default="active",
                max_length=16,
            ),
        ),
    ]
